Awesome books with javascript modules
mkaya13/Awesome-Books-with-ES6-Modules pull request #1
Opened 2022-10-31 13:18 UTC by mkaya13

- Codes are re-arranged and initialized with javascript modules.

2022-10-31 13:55 UTC, omarsalem7 requested changes
Hi @mkaya13 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- The Pull Request has a proper title. ✔️
- Correct git-flow ✔️

## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-31 13:55 UTC, omarsalem7 commented on modules/BookClass.js
> +/* eslint-disable import/no-cycle */
- [ ] Kindly remove this line and fix the linter errors because linter makes you write good code which follows best practices.

2022-10-31 13:55 UTC, omarsalem7 commented on modules/ShowandRemoveBooks.js
> +/* eslint-disable import/no-cycle */
- [ ] As stated above kindly remove this line also and fix the linters.

2022-10-31 13:55 UTC, omarsalem7 commented on modules/ShowandRemoveBooks.js
> +    // eslint-disable-next-line no-use-before-define
- [ ] Also remove this line and fix linters as stated above.

2022-10-31 13:55 UTC, omarsalem7 commented on index.js
> +  // showCurrentTime.textContent = curTime;
- [ ] It will be better if you remove the commented code from your codebase to make your code clean.

2022-11-01 00:16 UTC, Reem-lab approved these changes
# Hi @mkaya13,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯

<img src="https://media3.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>

## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up and functionality for js files✅
📌 Good commit messages ✅
📌 Professional README file ✅


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 00:30 UTC, merged